; Auto-generated. Do not edit!


(cl:in-package actions_quiz-msg)


;//! \htmlinclude CustomActionMsgFeedback.msg.html

(cl:defclass <CustomActionMsgFeedback> (roslisp-msg-protocol:ros-message)
  ((feedback
    :reader feedback
    :initarg :feedback
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass CustomActionMsgFeedback (<CustomActionMsgFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CustomActionMsgFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CustomActionMsgFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actions_quiz-msg:<CustomActionMsgFeedback> is deprecated: use actions_quiz-msg:CustomActionMsgFeedback instead.")))

(cl:ensure-generic-function 'feedback-val :lambda-list '(m))
(cl:defmethod feedback-val ((m <CustomActionMsgFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actions_quiz-msg:feedback-val is deprecated.  Use actions_quiz-msg:feedback instead.")
  (feedback m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CustomActionMsgFeedback>) ostream)
  "Serializes a message object of type '<CustomActionMsgFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'feedback) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CustomActionMsgFeedback>) istream)
  "Deserializes a message object of type '<CustomActionMsgFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'feedback) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CustomActionMsgFeedback>)))
  "Returns string type for a message object of type '<CustomActionMsgFeedback>"
  "actions_quiz/CustomActionMsgFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CustomActionMsgFeedback)))
  "Returns string type for a message object of type 'CustomActionMsgFeedback"
  "actions_quiz/CustomActionMsgFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CustomActionMsgFeedback>)))
  "Returns md5sum for a message object of type '<CustomActionMsgFeedback>"
  "be452bdb25132e643f85b55a53a6b2e3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CustomActionMsgFeedback)))
  "Returns md5sum for a message object of type 'CustomActionMsgFeedback"
  "be452bdb25132e643f85b55a53a6b2e3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CustomActionMsgFeedback>)))
  "Returns full string definition for message of type '<CustomActionMsgFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%std_msgs/String feedback~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CustomActionMsgFeedback)))
  "Returns full string definition for message of type 'CustomActionMsgFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%std_msgs/String feedback~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CustomActionMsgFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'feedback))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CustomActionMsgFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CustomActionMsgFeedback
    (cl:cons ':feedback (feedback msg))
))
