; Auto-generated. Do not edit!


(cl:in-package actions_quiz-msg)


;//! \htmlinclude CustomActionMsgGoal.msg.html

(cl:defclass <CustomActionMsgGoal> (roslisp-msg-protocol:ros-message)
  ((goal
    :reader goal
    :initarg :goal
    :type std_msgs-msg:String
    :initform (cl:make-instance 'std_msgs-msg:String)))
)

(cl:defclass CustomActionMsgGoal (<CustomActionMsgGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CustomActionMsgGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CustomActionMsgGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name actions_quiz-msg:<CustomActionMsgGoal> is deprecated: use actions_quiz-msg:CustomActionMsgGoal instead.")))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <CustomActionMsgGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader actions_quiz-msg:goal-val is deprecated.  Use actions_quiz-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CustomActionMsgGoal>) ostream)
  "Serializes a message object of type '<CustomActionMsgGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CustomActionMsgGoal>) istream)
  "Deserializes a message object of type '<CustomActionMsgGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CustomActionMsgGoal>)))
  "Returns string type for a message object of type '<CustomActionMsgGoal>"
  "actions_quiz/CustomActionMsgGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CustomActionMsgGoal)))
  "Returns string type for a message object of type 'CustomActionMsgGoal"
  "actions_quiz/CustomActionMsgGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CustomActionMsgGoal>)))
  "Returns md5sum for a message object of type '<CustomActionMsgGoal>"
  "08a998acc62f6e46d584d02104d1b4e4")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CustomActionMsgGoal)))
  "Returns md5sum for a message object of type 'CustomActionMsgGoal"
  "08a998acc62f6e46d584d02104d1b4e4")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CustomActionMsgGoal>)))
  "Returns full string definition for message of type '<CustomActionMsgGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%std_msgs/String goal~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CustomActionMsgGoal)))
  "Returns full string definition for message of type 'CustomActionMsgGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal~%std_msgs/String goal~%~%================================================================================~%MSG: std_msgs/String~%string data~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CustomActionMsgGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CustomActionMsgGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'CustomActionMsgGoal
    (cl:cons ':goal (goal msg))
))
