// Auto-generated. Do not edit!

// (in-package actions_quiz.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let std_msgs = _finder('std_msgs');

//-----------------------------------------------------------

class CustomActionMsgGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.goal = null;
    }
    else {
      if (initObj.hasOwnProperty('goal')) {
        this.goal = initObj.goal
      }
      else {
        this.goal = new std_msgs.msg.String();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type CustomActionMsgGoal
    // Serialize message field [goal]
    bufferOffset = std_msgs.msg.String.serialize(obj.goal, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type CustomActionMsgGoal
    let len;
    let data = new CustomActionMsgGoal(null);
    // Deserialize message field [goal]
    data.goal = std_msgs.msg.String.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += std_msgs.msg.String.getMessageSize(object.goal);
    return length;
  }

  static datatype() {
    // Returns string type for a message object
    return 'actions_quiz/CustomActionMsgGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '08a998acc62f6e46d584d02104d1b4e4';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    #goal
    std_msgs/String goal
    
    ================================================================================
    MSG: std_msgs/String
    string data
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new CustomActionMsgGoal(null);
    if (msg.goal !== undefined) {
      resolved.goal = std_msgs.msg.String.Resolve(msg.goal)
    }
    else {
      resolved.goal = new std_msgs.msg.String()
    }

    return resolved;
    }
};

module.exports = CustomActionMsgGoal;
