(cl:defpackage bb8_custom_service_message-srv
  (:use )
  (:export
   "BB8CUSTOMSERVICEMESSAGE"
   "<BB8CUSTOMSERVICEMESSAGE-REQUEST>"
   "BB8CUSTOMSERVICEMESSAGE-REQUEST"
   "<BB8CUSTOMSERVICEMESSAGE-RESPONSE>"
   "BB8CUSTOMSERVICEMESSAGE-RESPONSE"
  ))

